apply plugin: 'com.android.application'

android {
    namespace "erg.com.nioshheatindex"
    buildFeatures {
        buildConfig true
    }
    compileSdk 37

    defaultConfig {
        applicationId "erg.com.nioshheatindex"
        minSdk 26
        targetSdk 35
        versionCode 20
        versionName "3.4"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'

    // Adobe Analyticd
    implementation 'com.adobe.marketing.mobile:analytics:1.+'
    implementation 'com.adobe.marketing.mobile:userprofile:1.+'
    implementation 'com.adobe.marketing.mobile:sdk-core:1.+'
    //implementation files('src/main/libs/adobeMobileLibrary-4.18.2.jar')
    //testImplementation 'junit:junit:4.12'
}
