package erg.com.nioshheatindex;

import android.content.Context;
import android.graphics.Paint;
import android.graphics.Matrix;
import android.graphics.RectF;
import android.graphics.Shader;
import android.graphics.LinearGradient;
import android.graphics.RadialGradient;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Path;
import android.text.Layout;
import android.text.StaticLayout;
import android.text.TextPaint;
import java.util.Stack;
import java.util.Arrays;
import android.graphics.Typeface;



/**
 * Created by Roger Pingleton on Jun 24, 2021.
 * Copyright © 2021 NIOSH. All rights reserved.
 *
 * Generated by PaintCode
 * http://www.paintcodeapp.com
 *
 * @author Roger Pingleton
 */
public class StyleKitESDark2 {
    
    
    // Resizing Behavior
    public enum ResizingBehavior {
        AspectFit, //!< The content is proportionally resized to fit into the target rectangle.
        AspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
        Stretch, //!< The content is stretched to match the entire target rectangle.
        Center, //!< The content is centered in the target rectangle, but it is NOT resized.
    }
    
    // Canvas Drawings
    // Guage
    
    private static class CacheForHeatIndexESDark {
        private static Paint paint = new Paint();
        private static PaintCodeGradient gradient2 = null;
        private static RectF originalFrame = new RectF(0f, 0f, 300f, 180f);
        private static RectF resizedFrame = new RectF();
        private static RectF rectangleRect = new RectF();
        private static Path rectanglePath = new Path();
        private static RectF extremeBGRect = new RectF();
        private static Path extremeBGPath = new Path();
        private static RectF minBG2Rect = new RectF();
        private static Path minBG2Path = new Path();
        private static RectF highBG2Rect = new RectF();
        private static Path highBG2Path = new Path();
        private static RectF cautionHighestRect = new RectF();
        private static Path cautionHighestPath = new Path();
        private static RectF arcRect = new RectF();
        private static Path arcPath = new Path();
        private static PaintCodeLinearGradient arcPathGradient = new PaintCodeLinearGradient();
        private static RectF needleShapeRect = new RectF();
        private static Path needleShapePath = new Path();
        private static RectF minimalTextESRect = new RectF();
        private static TextPaint minimalTextESTextPaint = new TextPaint();
        private static PaintCodeStaticLayout minimalTextESStaticLayout = new PaintCodeStaticLayout();
        private static RectF extremeTextESRect = new RectF();
        private static TextPaint extremeTextESTextPaint = new TextPaint();
        private static PaintCodeStaticLayout extremeTextESStaticLayout = new PaintCodeStaticLayout();
        private static RectF highTextESRect = new RectF();
        private static TextPaint highTextESTextPaint = new TextPaint();
        private static PaintCodeStaticLayout highTextESStaticLayout = new PaintCodeStaticLayout();
        private static RectF feelsLikeTextESRect = new RectF();
        private static TextPaint feelsLikeTextESTextPaint = new TextPaint();
        private static PaintCodeStaticLayout feelsLikeTextESStaticLayout = new PaintCodeStaticLayout();
        private static RectF atTextESRect = new RectF();
        private static TextPaint atTextESTextPaint = new TextPaint();
        private static PaintCodeStaticLayout atTextESStaticLayout = new PaintCodeStaticLayout();
        private static RectF temperatureTextRect = new RectF();
        private static TextPaint temperatureTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout temperatureTextStaticLayout = new PaintCodeStaticLayout();
        private static RectF feelsLikeTextRect = new RectF();
        private static TextPaint feelsLikeTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout feelsLikeTextStaticLayout = new PaintCodeStaticLayout();
        private static RectF minimalTextRect = new RectF();
        private static TextPaint minimalTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout minimalTextStaticLayout = new PaintCodeStaticLayout();
        private static RectF highTextRect = new RectF();
        private static TextPaint highTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout highTextStaticLayout = new PaintCodeStaticLayout();
        private static RectF extremeTextRect = new RectF();
        private static TextPaint extremeTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout extremeTextStaticLayout = new PaintCodeStaticLayout();
        private static RectF atTextRect = new RectF();
        private static TextPaint atTextTextPaint = new TextPaint();
        private static PaintCodeStaticLayout atTextStaticLayout = new PaintCodeStaticLayout();
    }

public static void drawHeatIndexESDark(Canvas canvas, Context context, double needle, String feelsLikeTemp, boolean spanish, String time, boolean isDarkMode) {
    StyleKitESDark2.drawHeatIndexESDark(canvas, context, new RectF(0f, 0f, 300f, 180f), ResizingBehavior.AspectFit, needle, feelsLikeTemp, spanish, time, isDarkMode);
}

    public static void drawHeatIndexESDark(Canvas canvas, Context context, RectF targetFrame, ResizingBehavior resizing, double needle, String feelsLikeTemp, boolean spanish, String time, boolean isDarkMode) {
        // General Declarations
        Stack<Matrix> currentTransformation = new Stack<Matrix>();
        currentTransformation.push(new Matrix());
        Paint paint = CacheForHeatIndexESDark.paint;
        
        // Local Colors
        int yellow = Color.argb(255, 255, 225, 0);
        int red = Color.argb(255, 189, 32, 36);
        int black = Color.argb(255, 0, 0, 0);
        int grey = Color.argb(255, 230, 230, 230);
        int white = Color.argb(255, 255, 255, 255);
        int darkGrey = Color.argb(255, 73, 73, 73);
        int orange1 = Color.argb(255, 255, 121, 0);
        
        // Local Gradients
        if (CacheForHeatIndexESDark.gradient2 == null)
            CacheForHeatIndexESDark.gradient2 = new PaintCodeGradient(new int[]{red, PaintCodeColor.colorByBlendingColors(red, 0.5f, orange1), orange1, yellow}, new float[]{0f, 0.26f, 0.53f, 1f});
        PaintCodeGradient gradient2 = CacheForHeatIndexESDark.gradient2;
        
        // Local Variables
        boolean english = !spanish;
        int darkModeWhite = isDarkMode ? white : black;
        int minimalColorText = needle > 0f && needle < 0.3339f ? black : darkGrey;
        double needleExp = (1f - needle) * 180f - 90f;
        int highColorText = needle >= 0.3339f && needle < 0.6669f ? black : darkGrey;
        int darkModeBlack = isDarkMode ? black : white;
        String timees = "A las " + time;
        int warningColor = needle >= 0.3339f && needle < 0.6669f ? orange1 : grey;
        int minimalColor = needle > 0f && needle < 0.3339f ? yellow : grey;
        int extremeColorText = needle >= 0.6669f ? white : darkGrey;
        String timeen = "At " + time;
        int extremeColor = needle >= 0.6669f ? red : grey;
        
        // Resize to Target Frame
        canvas.save();
        RectF resizedFrame = CacheForHeatIndexESDark.resizedFrame;
        StyleKitESDark2.resizingBehaviorApply(resizing, CacheForHeatIndexESDark.originalFrame, targetFrame, resizedFrame);
        canvas.translate(resizedFrame.left, resizedFrame.top);
        canvas.scale(resizedFrame.width() / 300f, resizedFrame.height() / 180f);
        
        // Rectangle
        RectF rectangleRect = CacheForHeatIndexESDark.rectangleRect;
        rectangleRect.set(0f, 0f, 300f, 180f);
        Path rectanglePath = CacheForHeatIndexESDark.rectanglePath;
        rectanglePath.reset();
        rectanglePath.addRect(rectangleRect, Path.Direction.CW);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(darkModeBlack);
        canvas.drawPath(rectanglePath, paint);
        
        // ExtremeBG
        RectF extremeBGRect = CacheForHeatIndexESDark.extremeBGRect;
        extremeBGRect.set(225.25f, 25.25f, 300.61f, 148.25f);
        Path extremeBGPath = CacheForHeatIndexESDark.extremeBGPath;
        extremeBGPath.reset();
        extremeBGPath.moveTo(300.61f, 25.25f);
        extremeBGPath.cubicTo(300.61f, 25.25f, 300.61f, 140.07f, 300.61f, 140.07f);
        extremeBGPath.cubicTo(300.61f, 145.2f, 298f, 148f, 292.46f, 148.25f);
        extremeBGPath.lineTo(251.4f, 148.25f);
        extremeBGPath.cubicTo(249.89f, 124.73f, 240.25f, 103.41f, 225.25f, 87.04f);
        extremeBGPath.cubicTo(262.87f, 56.2f, 300.61f, 25.25f, 300.61f, 25.25f);
        extremeBGPath.lineTo(300.61f, 25.25f);
        extremeBGPath.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(extremeColor);
        canvas.drawPath(extremeBGPath, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2.5f);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(extremeBGPath, paint);
        canvas.restore();
        
        // MinBG2
        RectF minBG2Rect = CacheForHeatIndexESDark.minBG2Rect;
        minBG2Rect.set(0f, 2f, 104.75f, 149f);
        Path minBG2Path = CacheForHeatIndexESDark.minBG2Path;
        minBG2Path.reset();
        minBG2Path.moveTo(15.29f, 2f);
        minBG2Path.cubicTo(15.29f, 2f, 66.4f, 2f, 62f, 2f);
        minBG2Path.lineTo(104.75f, 73.41f);
        minBG2Path.lineTo(89f, 83f);
        minBG2Path.lineTo(70f, 104f);
        minBG2Path.lineTo(62f, 125f);
        minBG2Path.lineTo(57.5f, 149f);
        minBG2Path.lineTo(15.29f, 149f);
        minBG2Path.cubicTo(10.88f, 149f, 8.68f, 149f, 6.7f, 148.35f);
        minBG2Path.lineTo(6.31f, 148.25f);
        minBG2Path.cubicTo(3.73f, 147.31f, 1.69f, 145.27f, 0.75f, 142.69f);
        minBG2Path.cubicTo(0f, 140.32f, 0f, 138.12f, 0f, 133.71f);
        minBG2Path.lineTo(0f, 17.29f);
        minBG2Path.cubicTo(0f, 12.88f, 0f, 10.68f, 0.65f, 8.7f);
        minBG2Path.lineTo(0.75f, 8.31f);
        minBG2Path.cubicTo(1.69f, 5.73f, 3.73f, 3.69f, 6.31f, 2.75f);
        minBG2Path.cubicTo(8.68f, 2f, 10.88f, 2f, 15.29f, 2f);
        minBG2Path.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(minimalColor);
        canvas.drawPath(minBG2Path, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2.5f);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(minBG2Path, paint);
        canvas.restore();
        
        // HighBG2
        RectF highBG2Rect = CacheForHeatIndexESDark.highBG2Rect;
        highBG2Rect.set(62.5f, 2f, 239.5f, 73.32f);
        Path highBG2Path = CacheForHeatIndexESDark.highBG2Path;
        highBG2Path.reset();
        highBG2Path.moveTo(175.5f, 65f);
        highBG2Path.lineTo(150.5f, 61f);
        highBG2Path.lineTo(124.5f, 66f);
        highBG2Path.lineTo(104.5f, 73f);
        highBG2Path.lineTo(62.5f, 2f);
        highBG2Path.lineTo(239.5f, 2f);
        highBG2Path.lineTo(196.23f, 73.32f);
        highBG2Path.lineTo(175.5f, 65f);
        highBG2Path.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(warningColor);
        canvas.drawPath(highBG2Path, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2.5f);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(highBG2Path, paint);
        canvas.restore();
        
        // Caution-Highest
        RectF cautionHighestRect = CacheForHeatIndexESDark.cautionHighestRect;
        cautionHighestRect.set(196.08f, 2f, 300f, 152f);
        Path cautionHighestPath = CacheForHeatIndexESDark.cautionHighestPath;
        cautionHighestPath.reset();
        cautionHighestPath.moveTo(242f, 131f);
        cautionHighestPath.lineTo(232f, 108f);
        cautionHighestPath.lineTo(218f, 89f);
        cautionHighestPath.lineTo(196.08f, 74.75f);
        cautionHighestPath.lineTo(239f, 2f);
        cautionHighestPath.lineTo(284.71f, 2f);
        cautionHighestPath.cubicTo(289.12f, 2f, 291.32f, 2f, 293.3f, 2.65f);
        cautionHighestPath.lineTo(293.69f, 2.75f);
        cautionHighestPath.cubicTo(296.27f, 3.69f, 298.31f, 5.73f, 299.25f, 8.31f);
        cautionHighestPath.cubicTo(300f, 10.68f, 300f, 12.88f, 300f, 17.29f);
        cautionHighestPath.lineTo(300f, 136.71f);
        cautionHighestPath.cubicTo(300f, 141.12f, 300f, 143.32f, 299.35f, 145.3f);
        cautionHighestPath.lineTo(299.25f, 145.69f);
        cautionHighestPath.cubicTo(298.31f, 148.27f, 296.27f, 150.31f, 293.69f, 151.25f);
        cautionHighestPath.cubicTo(291.32f, 152f, 289.12f, 152f, 284.71f, 152f);
        cautionHighestPath.lineTo(244f, 152f);
        cautionHighestPath.lineTo(242f, 131f);
        cautionHighestPath.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(extremeColor);
        canvas.drawPath(cautionHighestPath, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2.5f);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(cautionHighestPath, paint);
        canvas.restore();
        
        // Arc
        RectF arcRect = CacheForHeatIndexESDark.arcRect;
        arcRect.set(49f, 54f, 251f, 154.5f);
        Path arcPath = CacheForHeatIndexESDark.arcPath;
        arcPath.reset();
        arcPath.moveTo(251f, 154.5f);
        arcPath.lineTo(235.87f, 154.5f);
        arcPath.cubicTo(235.87f, 107.31f, 197.43f, 69.05f, 150f, 69.05f);
        arcPath.cubicTo(102.57f, 69.05f, 64.13f, 107.31f, 64.13f, 154.5f);
        arcPath.lineTo(49f, 154.5f);
        arcPath.cubicTo(49f, 99f, 94.22f, 54f, 150f, 54f);
        arcPath.cubicTo(205.78f, 54f, 251f, 99f, 251f, 154.5f);
        arcPath.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setShader(CacheForHeatIndexESDark.arcPathGradient.get(gradient2, 251f, 104.25f, 49f, 104.25f));
        canvas.drawPath(arcPath, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2f);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(arcPath, paint);
        canvas.restore();
        
        // NeedleShape
        canvas.save();
        canvas.translate(150.05f, 150.62f);
        currentTransformation.peek().postTranslate(150.05f, 150.62f);
        canvas.rotate((float) -needleExp);
        currentTransformation.peek().postRotate((float) -needleExp);
        RectF needleShapeRect = CacheForHeatIndexESDark.needleShapeRect;
        needleShapeRect.set(-4.05f, -104.12f, 4.95f, -73.62f);
        Path needleShapePath = CacheForHeatIndexESDark.needleShapePath;
        needleShapePath.reset();
        needleShapePath.moveTo(0.46f, -104.11f);
        needleShapePath.cubicTo(0.45f, -104.12f, 4.73f, -99.9f, 4.73f, -99.9f);
        needleShapePath.cubicTo(4.73f, -99.9f, 4.54f, -99.08f, 4.28f, -98.02f);
        needleShapePath.lineTo(4.95f, -98.02f);
        needleShapePath.lineTo(4.95f, -73.62f);
        needleShapePath.lineTo(-4.05f, -73.62f);
        needleShapePath.lineTo(-4.05f, -98.02f);
        needleShapePath.lineTo(-3.37f, -98.02f);
        needleShapePath.cubicTo(-3.63f, -99.08f, -3.83f, -99.9f, -3.83f, -99.9f);
        needleShapePath.cubicTo(-3.83f, -99.9f, -1.16f, -102.53f, -0.03f, -103.63f);
        needleShapePath.cubicTo(0.26f, -103.93f, 0.45f, -104.12f, 0.45f, -104.12f);
        needleShapePath.lineTo(0.46f, -104.11f);
        needleShapePath.close();
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(darkModeWhite);
        canvas.drawPath(needleShapePath, paint);
        
        paint.reset();
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        paint.setStrokeWidth(2f);
        paint.setStrokeCap(Paint.Cap.ROUND);
        paint.setStrokeMiter(10f);
        canvas.save();
        paint.setStyle(Paint.Style.STROKE);
        paint.setColor(darkModeBlack);
        canvas.drawPath(needleShapePath, paint);
        canvas.restore();
        canvas.restore();
        
        // MinimalTextES
        if (spanish) {
            RectF minimalTextESRect = CacheForHeatIndexESDark.minimalTextESRect;
            minimalTextESRect.set(0f, 48f, 87f, 89f);
            TextPaint minimalTextESTextPaint = CacheForHeatIndexESDark.minimalTextESTextPaint;
            minimalTextESTextPaint.reset();
            minimalTextESTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            minimalTextESTextPaint.setColor(minimalColorText);
            //minimalTextESTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            minimalTextESTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            minimalTextESTextPaint.setTextSize(13f);
            StaticLayout minimalTextESStaticLayout = CacheForHeatIndexESDark.minimalTextESStaticLayout.get((int) minimalTextESRect.width(), Layout.Alignment.ALIGN_CENTER, "Precaución", minimalTextESTextPaint);
            canvas.save();
            canvas.clipRect(minimalTextESRect);
            canvas.translate(minimalTextESRect.left, minimalTextESRect.top + (minimalTextESRect.height() - minimalTextESStaticLayout.getHeight()) / 2f);
            minimalTextESStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // ExtremeTextES
        if (spanish) {
            RectF extremeTextESRect = CacheForHeatIndexESDark.extremeTextESRect;
            extremeTextESRect.set(221f, 41f, 296f, 93f);
            TextPaint extremeTextESTextPaint = CacheForHeatIndexESDark.extremeTextESTextPaint;
            extremeTextESTextPaint.reset();
            extremeTextESTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            extremeTextESTextPaint.setColor(extremeColorText);
            //extremeTextESTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            extremeTextESTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            extremeTextESTextPaint.setTextSize(13f);
            StaticLayout extremeTextESStaticLayout = CacheForHeatIndexESDark.extremeTextESStaticLayout.get((int) extremeTextESRect.width(), Layout.Alignment.ALIGN_CENTER, "Peligro", extremeTextESTextPaint);
            canvas.save();
            canvas.clipRect(extremeTextESRect);
            canvas.translate(extremeTextESRect.left, extremeTextESRect.top + (extremeTextESRect.height() - extremeTextESStaticLayout.getHeight()) / 2f);
            extremeTextESStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // HighTextES
        if (spanish) {
            RectF highTextESRect = CacheForHeatIndexESDark.highTextESRect;
            highTextESRect.set(97f, 7f, 202f, 48f);
            TextPaint highTextESTextPaint = CacheForHeatIndexESDark.highTextESTextPaint;
            highTextESTextPaint.reset();
            highTextESTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            highTextESTextPaint.setColor(highColorText);
            //highTextESTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            highTextESTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            highTextESTextPaint.setTextSize(13f);
            StaticLayout highTextESStaticLayout = CacheForHeatIndexESDark.highTextESStaticLayout.get((int) highTextESRect.width(), Layout.Alignment.ALIGN_CENTER, "Advertencia", highTextESTextPaint);
            canvas.save();
            canvas.clipRect(highTextESRect);
            canvas.translate(highTextESRect.left, highTextESRect.top + (highTextESRect.height() - highTextESStaticLayout.getHeight()) / 2f);
            highTextESStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // FeelsLikeTextES
        if (spanish) {
            RectF feelsLikeTextESRect = CacheForHeatIndexESDark.feelsLikeTextESRect;
            feelsLikeTextESRect.set(61f, 106f, 238f, 128f);
            TextPaint feelsLikeTextESTextPaint = CacheForHeatIndexESDark.feelsLikeTextESTextPaint;
            feelsLikeTextESTextPaint.reset();
            feelsLikeTextESTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            feelsLikeTextESTextPaint.setColor(darkModeWhite);
            feelsLikeTextESTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            feelsLikeTextESTextPaint.setTextSize(14.5f);
            StaticLayout feelsLikeTextESStaticLayout = CacheForHeatIndexESDark.feelsLikeTextESStaticLayout.get((int) feelsLikeTextESRect.width(), Layout.Alignment.ALIGN_CENTER, "Sensación Térmica", feelsLikeTextESTextPaint);
            canvas.save();
            canvas.clipRect(feelsLikeTextESRect);
            canvas.translate(feelsLikeTextESRect.left, feelsLikeTextESRect.top + (feelsLikeTextESRect.height() - feelsLikeTextESStaticLayout.getHeight()) / 2f);
            feelsLikeTextESStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // AtTextES
        if (spanish) {
            RectF atTextESRect = CacheForHeatIndexESDark.atTextESRect;
            atTextESRect.set(87f, 78f, 211f, 105f);
            TextPaint atTextESTextPaint = CacheForHeatIndexESDark.atTextESTextPaint;
            atTextESTextPaint.reset();
            atTextESTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            atTextESTextPaint.setColor(darkModeWhite);
            atTextESTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            atTextESTextPaint.setTextSize(12.5f);
            StaticLayout atTextESStaticLayout = CacheForHeatIndexESDark.atTextESStaticLayout.get((int) atTextESRect.width(), Layout.Alignment.ALIGN_CENTER, timees, atTextESTextPaint);
            canvas.save();
            canvas.clipRect(atTextESRect);
            canvas.translate(atTextESRect.left, atTextESRect.top + (atTextESRect.height() - atTextESStaticLayout.getHeight()) / 2f);
            atTextESStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // TemperatureText
        RectF temperatureTextRect = CacheForHeatIndexESDark.temperatureTextRect;
        temperatureTextRect.set(64f, 128f, 237f, 185f);
        TextPaint temperatureTextTextPaint = CacheForHeatIndexESDark.temperatureTextTextPaint;
        temperatureTextTextPaint.reset();
        temperatureTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
        temperatureTextTextPaint.setColor(darkModeWhite);
        temperatureTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
        temperatureTextTextPaint.setTextSize(36f);
        StaticLayout temperatureTextStaticLayout = CacheForHeatIndexESDark.temperatureTextStaticLayout.get((int) temperatureTextRect.width(), Layout.Alignment.ALIGN_CENTER, feelsLikeTemp, temperatureTextTextPaint);
        canvas.save();
        canvas.clipRect(temperatureTextRect);
        canvas.translate(temperatureTextRect.left, temperatureTextRect.top + (temperatureTextRect.height() - temperatureTextStaticLayout.getHeight()) / 2f);
        temperatureTextStaticLayout.draw(canvas);
        canvas.restore();
        
        // FeelsLikeText
        if (english) {
            RectF feelsLikeTextRect = CacheForHeatIndexESDark.feelsLikeTextRect;
            feelsLikeTextRect.set(76f, 101f, 225f, 128f);
            TextPaint feelsLikeTextTextPaint = CacheForHeatIndexESDark.feelsLikeTextTextPaint;
            feelsLikeTextTextPaint.reset();
            feelsLikeTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            feelsLikeTextTextPaint.setColor(darkModeWhite);
            feelsLikeTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            feelsLikeTextTextPaint.setTextSize(20f);
            StaticLayout feelsLikeTextStaticLayout = CacheForHeatIndexESDark.feelsLikeTextStaticLayout.get((int) feelsLikeTextRect.width(), Layout.Alignment.ALIGN_CENTER, "Feels Like", feelsLikeTextTextPaint);
            canvas.save();
            canvas.clipRect(feelsLikeTextRect);
            canvas.translate(feelsLikeTextRect.left, feelsLikeTextRect.top + (feelsLikeTextRect.height() - feelsLikeTextStaticLayout.getHeight()) / 2f);
            feelsLikeTextStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // MinimalText
        if (english) {
            RectF minimalTextRect = CacheForHeatIndexESDark.minimalTextRect;
            minimalTextRect.set(6f, 48f, 75f, 89f);
            TextPaint minimalTextTextPaint = CacheForHeatIndexESDark.minimalTextTextPaint;
            minimalTextTextPaint.reset();
            minimalTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            minimalTextTextPaint.setColor(minimalColorText);
            //minimalTextTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            minimalTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            minimalTextTextPaint.setTextSize(14f);
            StaticLayout minimalTextStaticLayout = CacheForHeatIndexESDark.minimalTextStaticLayout.get((int) minimalTextRect.width(), Layout.Alignment.ALIGN_CENTER, "Caution", minimalTextTextPaint);
            canvas.save();
            canvas.clipRect(minimalTextRect);
            canvas.translate(minimalTextRect.left, minimalTextRect.top + (minimalTextRect.height() - minimalTextStaticLayout.getHeight()) / 2f);
            minimalTextStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // HighText
        if (english) {
            RectF highTextRect = CacheForHeatIndexESDark.highTextRect;
            highTextRect.set(116f, 8f, 185f, 49f);
            TextPaint highTextTextPaint = CacheForHeatIndexESDark.highTextTextPaint;
            highTextTextPaint.reset();
            highTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            highTextTextPaint.setColor(highColorText);
            //highTextTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            highTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            highTextTextPaint.setTextSize(14f);
            StaticLayout highTextStaticLayout = CacheForHeatIndexESDark.highTextStaticLayout.get((int) highTextRect.width(), Layout.Alignment.ALIGN_CENTER, "Warning", highTextTextPaint);
            canvas.save();
            canvas.clipRect(highTextRect);
            canvas.translate(highTextRect.left, highTextRect.top + (highTextRect.height() - highTextStaticLayout.getHeight()) / 2f);
            highTextStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // ExtremeText
        if (english) {
            RectF extremeTextRect = CacheForHeatIndexESDark.extremeTextRect;
            extremeTextRect.set(228f, 40f, 297f, 89f);
            TextPaint extremeTextTextPaint = CacheForHeatIndexESDark.extremeTextTextPaint;
            extremeTextTextPaint.reset();
            extremeTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            extremeTextTextPaint.setColor(extremeColorText);
            //extremeTextTextPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "SFNS.ttf"));
            extremeTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            extremeTextTextPaint.setTextSize(14f);
            StaticLayout extremeTextStaticLayout = CacheForHeatIndexESDark.extremeTextStaticLayout.get((int) extremeTextRect.width(), Layout.Alignment.ALIGN_CENTER, "Danger", extremeTextTextPaint);
            canvas.save();
            canvas.clipRect(extremeTextRect);
            canvas.translate(extremeTextRect.left, extremeTextRect.top + (extremeTextRect.height() - extremeTextStaticLayout.getHeight()) / 2f);
            extremeTextStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        // AtText
        if (english) {
            RectF atTextRect = CacheForHeatIndexESDark.atTextRect;
            atTextRect.set(90.5f, 77f, 209.5f, 104f);
            TextPaint atTextTextPaint = CacheForHeatIndexESDark.atTextTextPaint;
            atTextTextPaint.reset();
            atTextTextPaint.setFlags(Paint.ANTI_ALIAS_FLAG);
            atTextTextPaint.setColor(darkModeWhite);
            atTextTextPaint.setTypeface(Typeface.create((String) null, Typeface.NORMAL));
            atTextTextPaint.setTextSize(13f);
            StaticLayout atTextStaticLayout = CacheForHeatIndexESDark.atTextStaticLayout.get((int) atTextRect.width(), Layout.Alignment.ALIGN_CENTER, timeen, atTextTextPaint);
            canvas.save();
            canvas.clipRect(atTextRect);
            canvas.translate(atTextRect.left, atTextRect.top + (atTextRect.height() - atTextStaticLayout.getHeight()) / 2f);
            atTextStaticLayout.draw(canvas);
            canvas.restore();
        }
        
        canvas.restore();
    }
    
    
    // Resizing Behavior
    public static void resizingBehaviorApply(ResizingBehavior behavior, RectF rect, RectF target, RectF result) {
        if (rect.equals(target) || target == null) {
            result.set(rect);
            return;
        }
        
        if (behavior == ResizingBehavior.Stretch) {
            result.set(target);
            return;
        }
        
        float xRatio = Math.abs(target.width() / rect.width());
        float yRatio = Math.abs(target.height() / rect.height());
        float scale = 0f;
        
        switch (behavior) {
            case AspectFit: {
                scale = Math.min(xRatio, yRatio);
                break;
            }
            case AspectFill: {
                scale = Math.max(xRatio, yRatio);
                break;
            }
            case Center: {
                scale = 1f;
                break;
            }
        }
        
        float newWidth = Math.abs(rect.width() * scale);
        float newHeight = Math.abs(rect.height() * scale);
        result.set(target.centerX() - newWidth / 2,
            target.centerY() - newHeight / 2,
            target.centerX() + newWidth / 2,
            target.centerY() + newHeight / 2);
    }
    
    
}

class PaintCodeColor extends Color {
    private static float[] ColorToHSV(int originalColor) {
        float hsv[] = new float[3];
        RGBToHSV(red(originalColor), green(originalColor), blue(originalColor), hsv);
        return hsv;
    }
    
    public static int colorByChangingHue(int originalColor, float newHue) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[0] = newHue;
        return HSVToColor(alpha(originalColor), hsv);
    }
    
    public static int colorByChangingSaturation(int originalColor, float newSaturation) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[1] = newSaturation;
        return HSVToColor(alpha(originalColor), hsv);
    }
    
    public static int colorByChangingValue(int originalColor, float newValue) {
        float hsv[] = ColorToHSV(originalColor);
        hsv[2] = newValue;
        return HSVToColor(alpha(originalColor), hsv);
    }
    
    public static float hue(int color) {
        return ColorToHSV(color)[0];
    }
    
    public static float saturation(int color) {
        return ColorToHSV(color)[1];
    }
    
    public static float brightness(int color) {
        return ColorToHSV(color)[2];
    }
    
    public static int colorByChangingAlpha(int color, int newAlpha) {
        return argb(newAlpha, red(color), green(color), blue(color));
    }
    
    public static int colorByBlendingColors(int c1, float ratio, int c2) {
        return argb((int) ((1f - ratio) * alpha(c1) + ratio * alpha(c2)),
            (int) ((1f - ratio) * red(c1) + ratio * red(c2)),
            (int) ((1f - ratio) * green(c1) + ratio * green(c2)),
            (int) ((1f - ratio) * blue(c1) + ratio * blue(c2)));
    }
    
    public static int colorByApplyingHighlight(int color, float ratio) {
        return colorByBlendingColors(color, ratio, colorByChangingAlpha(WHITE, alpha(color)));
    }
    
    public static int colorByApplyingShadow(int color, float ratio) {
        return colorByBlendingColors(color, ratio, colorByChangingAlpha(BLACK, alpha(color)));
    }
}

class PaintCodeGradient {
    private int[] colors;
    private float[] positions;
    
    public PaintCodeGradient(int[] colors, float[] positions) {
        if (positions == null) {
            int steps = colors.length;
            positions = new float[steps];
            for (int i = 0; i < steps; i++)
                positions[i] = (float) i / (steps - 1);
        }
        
        this.colors = colors;
        this.positions = positions;
    }
    
    public LinearGradient linearGradient(float x0, float y0, float x1, float y1) {
        return new LinearGradient(x0, y0, x1, y1, this.colors, this.positions, Shader.TileMode.CLAMP);
    }
    
    public RadialGradient radialGradient(float startX, float startY, float startRadius, float endX, float endY, float endRadius) {
        int steps = this.colors.length;
        float[] positions = new float[steps];
        
        if (startRadius > endRadius) {
            float ratio = endRadius / startRadius;
            int[] colors = new int[steps];
            
            for (int i = 0; i < steps; i++) {
                colors[i] = this.colors[steps - i - 1];
                positions[i] = (1 - this.positions[steps - i - 1]) * (1 - ratio) + ratio;
            }
            
            return new RadialGradient(endX, endY, startRadius, colors, positions, Shader.TileMode.CLAMP);
        } else {
            float ratio = startRadius / endRadius;
            
            for (int i = 0; i < steps; i++) {
                positions[i] = this.positions[i] * (1 - ratio) + ratio;
            }
            
            return new RadialGradient(startX, startY, endRadius, this.colors, positions, Shader.TileMode.CLAMP);
        }
    }
    
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof PaintCodeGradient))
            return false;
        PaintCodeGradient other = (PaintCodeGradient) obj;
        return Arrays.equals(this.colors, other.colors) && Arrays.equals(this.positions, other.positions);
    }
}


class PaintCodeLinearGradient {
    private LinearGradient shader;
    private PaintCodeGradient paintCodeGradient;
    private float x0, y0, x1, y1;
    LinearGradient get(PaintCodeGradient paintCodeGradient, float x0, float y0, float x1, float y1) {
        if (this.shader == null || this.x0 != x0 || this.y0 != y0 || this.x1 != x1 || this.y1 != y1 || !this.paintCodeGradient.equals(paintCodeGradient)) {
            this.x0 = x0;
            this.y0 = y0;
            this.x1 = x1;
            this.y1 = y1;
            this.paintCodeGradient = paintCodeGradient;
            this.shader = paintCodeGradient.linearGradient(x0, y0, x1, y1);
        }
        return this.shader;
    }
}


class PaintCodeStaticLayout {
    private StaticLayout layout;
    private int width;
    private Layout.Alignment alignment;
    private CharSequence source;
    private TextPaint paint;
    
    StaticLayout get(int width, Layout.Alignment alignment, CharSequence source, TextPaint paint) {
        if (this.layout == null || this.width != width || this.alignment != alignment || !this.source.equals(source) || !this.paint.equals(paint)) {
            this.width = width;
            this.alignment = alignment;
            this.source = source;
            this.paint = paint;
            this.layout = new StaticLayout(source, paint, width, alignment, 1, 0, false);
        }
        return this.layout;
    }
}
